name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name:
      run: sudo apt install build-essential libx11-dev libglfw3-dev libglfw3 xorg-dev
    - name: Submodules
      run: git submodule update --init --recursive
    - name: make
      run: make
